zuul:
  routes:
    serviceSimple:
      path: /greeting/simple
      url: forward:/
    serviceAdvanced:
      path: /greeting/advanced
      url: forward:/
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      serviceSimple:
      - limit: 5
        refresh-interval: 60
        type:
        - origin
      serviceAdvanced:
      - limit: 1
        refresh-interval: 2
        type:
        - origin
  strip-prefix: true

spring.h2.console.enabled: true
spring.h2.console.path: /h2

# Server timeout
zuul.host.connect-timeout-millis: 2000
zuul.host.connection-request-timeout-millis: 2000
zuul.host.socket-timeout-millis: 2000
#Application security
zuul.ignored-headers: Access-Control-Allow-Origin, Authentication
